#version: '3'
#
#services:
#  ml_processor_app:
#    build:
#      context: ./ml_processor
#    depends_on:
#      - redis
#
#  redis:
#    image: "redis:latest"
#    ports:
#      - "6379:6379"
#
#  celery_worker:
#    build:
#      context: .
#    depends_on:
#      - redis
#      - ml_processor_app
#    command: celery -A ml_processor worker --loglevel=info
